### ISSUE TITLE
Login screen

### ISSUE THREAD

**Issue by cbrevik** [cbrevik/some-project-name#4]
Make a login screen which includes a button, and an input for ditt and datt.

# Akseptansekriterier
- [ ] Should be accessible
- [ ] Must fit within a modal

# TODO:
- [ ] Design a login screen
- [ ] Login service must be developed
- [ ] Screen developed
- [ ]  

# Design skisser
![image](https://user-images.githubusercontent.com/4932625/133765137-c25f1a0f-a24c-461f-9df3-f190802cbddc.png)

**Comment by cbrevik** [comment]
@cbrevik design er klart, kjør på med utivkøigj
